# Option 1 - Modern version (Recommended)
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7188:7188"
    # Add healthcheck for better container monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7188/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Restart policy for better reliability
    restart: unless-stopped
    # Add reasonable resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G