# Generated by Django 2.1.7 on 2024-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('First', 'First')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr'), ('Mr.', 'Mr'), ('Prof Dr.', 'Prof Dr'), ('Mrs.', 'Mrs'), ('Ms.', 'Ms')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('First', 'First')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Visiting', 'Visiting'), ('Permanent', 'Permanent'), ('Contract', 'Contract')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr'), ('Mr.', 'Mr'), ('Prof Dr.', 'Prof Dr'), ('Mrs.', 'Mrs'), ('Ms.', 'Ms')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
    ]
