# Generated by Django 2.1.7 on 2024-07-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20240707_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('Second', 'Second'), ('First', 'First'), ('Third', 'Third')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs'), ('Ms.', 'Ms'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Masters', 'Masters'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('Second', 'Second'), ('First', 'First'), ('Third', 'Third')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs'), ('Ms.', 'Ms'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Masters', 'Masters'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma')], default='MSc', max_length=30),
        ),
    ]
