# Generated by Django 2.1.7 on 2024-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20240718_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Second', 'Second')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Second', 'Second')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Visiting', 'Visiting'), ('Contract', 'Contract'), ('Permanent', 'Permanent')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
    ]
