# Generated by Django 2.1.7 on 2024-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20240718_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Dr.', 'Dr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma'), ('Masters', 'Masters')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Dr.', 'Dr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma'), ('Masters', 'Masters')], default='MSc', max_length=30),
        ),
    ]
