# Generated by Django 5.0.7 on 2025-01-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_teacher_is_coordinator_teacher_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_coordinator',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Second', 'Second'), ('First', 'First'), ('Fourth', 'Fourth'), ('Third', 'Third')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('Diploma', 'Diploma')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.teacher'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Second', 'Second'), ('First', 'First'), ('Fourth', 'Fourth'), ('Third', 'Third')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Visiting', 'Visiting'), ('Permanent', 'Permanent'), ('Contract', 'Contract')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('Diploma', 'Diploma')], default='MSc', max_length=30),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
